name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: faiqbrinatta
          outputs: |
            dist/github-snake.svg?color_snake=#00F7FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353
            dist/github-snake-dark.svg?color_snake=#00F7FF&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
